name: Run Flaky Acceptance Tests
permissions: read-all
on:
  workflow_dispatch:
    inputs:
      runs:
        description: "Number of times to run test"
        required: true
        default: 50
      testsuite:
        description: "Test suite to run"
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    name: Build the app, and store build files as an artifact
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository so that local actions can be used
        uses: actions/checkout@v4
      - name: Merge develop and set up dependencies
        uses: ./.github/actions/merge-develop-and-set-up-dependencies
      - name: Generate build files
        uses: ./.github/actions/generate-build-files

  build-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

    steps:
      - name: Generate matrix
        id: set-matrix
        run: |
          RUNS=${{ github.event.inputs.runs }}
          LIST=$(seq -s ',' $RUNS)
          echo "matrix=[${LIST}]" >> $GITHUB_OUTPUT

  acceptance_test_with_python_installation:
    needs: [build]
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        suite: 
          - name: ${{ github.event.inputs.testsuite }}
        runs: ${{ fromJson(needs.build-matrix.outputs.matrix) }}
        mobile: [false, true]
    name: ${{ matrix.mobile && 'Mobile' || 'Desktop' }} Acceptance Test ${{ matrix.suite.name }}

    steps:
      - name: Checkout repository so that local actions can be used
        uses: actions/checkout@v4
      - name: Merge develop and set up dependencies
        uses: ./.github/actions/merge-develop-and-set-up-dependencies
      - name: Generate build files
        uses: ./.github/actions/generate-build-files
      - name: Generate modified suite name for artifacts
        id: generate_suite_name_for_artifacts
        # Replace slashes in the filename with underscores.
        run: |
          SUITE_NAME=${{ matrix.suite.name }}-${{ matrix.runs }}-${{ matrix.mobile }}
          echo "MODIFIED_SUITE_NAME=${SUITE_NAME//\//_}" >> $GITHUB_OUTPUT

      - name: Run Desktop Acceptance Test ${{ matrix.suite.name }}
        run: >
          set -o pipefail;
          VIDEO_RECORDING_IS_ENABLED=1
          xvfb-run -a --server-args="-screen 0, 1920x1080x24"
          python -m scripts.run_acceptance_tests
          --skip-build --suite=${{ matrix.suite.name }} --prod_env ${{ matrix.mobile == 'true' && '--mobile' || '' }}

      - name: Upload ${{ matrix.mobile && 'Mobile' || 'Desktop' }} test recordings as Artifacts
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{steps.generate_suite_name_for_artifacts.outputs.MODIFIED_SUITE_NAME}}
          path: /home/runner/work/oppia/oppia_full_stack_test_video_recordings/acceptance

      - name: Upload test failure screenshots as artifacts
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{steps.generate_suite_name_for_artifacts.outputs.MODIFIED_SUITE_NAME}}-failure-screenshots
          path: /home/runner/work/oppia/oppia_full_stack_test_failure_screenshots/acceptance
        # TODO(#22667): We are running this step twice, as snapshot gets deleted if 2nd attempt passes.

      - name: Upload diff screenshots as an artifact
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: diff-snapshots-${{steps.generate_suite_name_for_artifacts.outputs.MODIFIED_SUITE_NAME}}
          # Note: The path must be kept in sync with the one specified in
          # core/tests/puppeteer-acceptance-tests/utilities/common/puppeteer-utils.ts
          path: /home/runner/work/oppia/oppia/core/tests/puppeteer-acceptance-tests/diff-snapshots
