name: Run CI Checks
permissions: read-all
on:
  push:
    branches:
      - develop
      - release-*
  pull_request:
    branches:
      - develop
      - release-*
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true
jobs:
  job_1:
    name: Run all tests
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository so that local actions can be used
        uses: actions/checkout@v4
      - name: Merge develop and set up dependencies
        uses: ./.github/actions/merge-develop-and-set-up-dependencies
      - name: Describe filesystem
        run: |
          pwd
          ls /home/runner/work
          ls /home/runner/work/oppia
          ls /home/runner/work/oppia/oppia
          echo $GITHUB_WORKSPACE
      - name: Suppress ENOSPC error from chokidar file watcher. See https://stackoverflow.com/a/32600959.
        run: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
      - name: Reinstall Pip
        run: >
          python -m pip uninstall -y pip;
          wget https://bootstrap.pypa.io/get-pip.py;
          python get-pip.py pip==24.3.1

      - name: Run frontend tests (attempt ${{ matrix.num_runs }})
        id: run_frontend_tests
        run: python -m scripts.run_frontend_tests --check_coverage
      - name: Upload frontend coverage reports as an artifact
        if: ${{ steps.run_frontend_tests.outputs.WORKFLOW_STATUS == 'failure' }}
        uses: actions/upload-artifact@v4
        with:
          name: frontend-coverage-${{ matrix.num_runs }}
          path: /home/runner/work/oppia/karma_coverage_reports
    permissions:
      pull-requests: write
