name: WALL·E

permissions:
  contents: write # Needed to push screenshots
  pull-requests: read

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  acceptance-tests:
    if: startsWith(github.event.pull_request.title, 'Screenshot') || startsWith(github.event.pull_request.title, 'Debug')
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        suite:
          - name: voiceover-submitter/create-delete-and-update-status-of-voiceovers-of-the-explorations
          - name: voiceover-admin/assign-unassign-voiceover-artist-to-an-exploration
        prod_env: ["", "--prod_env"]
        mobile: ["", "--mobile"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Merge develop and set up dependencies
        uses: ./.github/actions/merge-develop-and-set-up-dependencies

      - name: Generate build files
        uses: ./.github/actions/generate-build-files

      - name: Run Acceptance Tests (${{ matrix.prod_env == '' && 'D' || 'P' }}${{ matrix.mobile == '' && 'D' || 'M'}})
        run: >
          set -o pipefail;
          VIDEO_RECORDING_IS_ENABLED=1
          xvfb-run -a --server-args="-screen 0, 1920x1080x24"
          python -m scripts.run_acceptance_tests
          --suite=${{ matrix.suite.name }} ${{ matrix.prod_env }} ${{ matrix.mobile }}
          | tee desktop_acceptance_test_${{ steps.generate_suite_name_for_artifacts.outputs.MODIFIED_SUITE_NAME }}.log || exit 0

      - name: Commit and push screenshots
        if: startsWith(github.event.pull_request.title, 'Screenshot')
        run: |
          BRANCH="${GITHUB_HEAD_REF}-new-wall-e"

          # Create branch if not exists
          git fetch origin $BRANCH || true
          git checkout -B $BRANCH

          # Copy or move your generated screenshots to repo folder
          # Example: cp -r /path/to/screenshots ./screenshots

          git add core/tests/puppeteer-acceptance-tests/specs/**/*.png
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -m "Update screenshots for ${{ github.event.pull_request.title }}" || echo "No changes to commit"
          git push origin $BRANCH --force
